services:
  server:
    build: .
    container_name: mytask-server
    restart: on-failure
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./:/mytask_server
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - SERVER_PORT=${SERVER_PORT}