# Generated by Django 5.1.2 on 2024-10-30 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_parent_alter_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='parent',
            new_name='parent_uuid',
        ),
    ]
