# Generated by Django 5.1.3 on 2024-12-03 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_is_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='parent_uuid',
            new_name='parent',
        ),
    ]
