# Generated by Django 5.1.3 on 2024-12-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_uuid_task_id_rename_parent_uuid_task_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
        migrations.AddField(
            model_name='task',
            name='parent_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
